/**
 * @module cli/commands/env
 * @description Environment management: init, check, keypair operations.
 */

import { Command } from "commander";
import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";
import { log, output } from "../logger";

/**
 * Load a keypair from a file path or inline string.
 * Standalone version that doesn't require CliConfig.
 */
function loadKeypairFromSource(source: string): import("@solana/web3.js").Keypair {
  const fs = require("fs");
  const { Keypair } = require("@solana/web3.js") as typeof import("@solana/web3.js");

  // Try as file path
  if (fs.existsSync(source)) {
    const raw = JSON.parse(fs.readFileSync(source, "utf-8"));
    return Keypair.fromSecretKey(Uint8Array.from(raw));
  }

  // Try as JSON array string
  try {
    const arr = JSON.parse(source);
    if (Array.isArray(arr)) {
      return Keypair.fromSecretKey(Uint8Array.from(arr));
    }
  } catch {
    // not JSON
  }

  // Try base64
  const decoded = Buffer.from(source, "base64");
  if (decoded.length === 64) {
    return Keypair.fromSecretKey(decoded);
  }

  throw new Error(`Cannot parse keypair from: ${source.slice(0, 20)}...`);
}

const ENV_TEMPLATE_FULL = `# ─── Synapse SAP Environment ───────────────────────────
# Generated by synapse-sap CLI

# RPC endpoints
SAP_RPC_URL=https://api.mainnet-beta.solana.com
SAP_FALLBACK_RPC_URL=

# Cluster & program
SAP_CLUSTER=mainnet-beta
SAP_PROGRAM_ID=SAPpUhsWLJG1FfkGRcXagEDMrMsWGjbky7AyhGpFETZ

# Agent keypair (path to JSON or base58 private key)
SAP_KEYPAIR=

# x402 payment settings
SAP_X402_ENDPOINT=
SAP_X402_NETWORK=solana:mainnet-beta

# Token settings
SAP_TOKEN_MINT=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
SAP_TOKEN_DECIMALS=6
SAP_TOKEN_TYPE=SPL

# Optional: PostgreSQL indexer
SAP_POSTGRES_URL=
SAP_POSTGRES_SCHEMA=synapse_sap

# Optional: Redis cache
SAP_REDIS_URL=

# Optional: Plugin discovery
SAP_PLUGIN_REGISTRY_URL=
`;

const ENV_TEMPLATE_DEVNET = `# ─── Synapse SAP Environment (Devnet) ─────────────────
# Generated by synapse-sap CLI

SAP_RPC_URL=https://api.devnet.solana.com
SAP_FALLBACK_RPC_URL=
SAP_CLUSTER=devnet
SAP_PROGRAM_ID=SAPpUhsWLJG1FfkGRcXagEDMrMsWGjbky7AyhGpFETZ
SAP_KEYPAIR=
SAP_X402_ENDPOINT=
SAP_X402_NETWORK=solana:devnet
SAP_TOKEN_MINT=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
SAP_TOKEN_DECIMALS=6
SAP_TOKEN_TYPE=SPL
`;

const REQUIRED_VARS = [
  "SAP_RPC_URL",
  "SAP_CLUSTER",
  "SAP_PROGRAM_ID",
];

const SENSITIVE_VARS = [
  "SAP_KEYPAIR",
  "SAP_POSTGRES_URL",
  "SAP_REDIS_URL",
];

export function registerEnvCommands(program: Command): void {
  const env = program
    .command("env")
    .description("Environment & keypair management");

  // ── env init ────────────────────────────────────
  env
    .command("init")
    .description("Generate a .env file from template")
    .option("--force", "Overwrite existing .env file")
    .option("--template <name>", "Template: full | devnet", "full")
    .option("--out <path>", "Output path", ".env")
    .action(async (opts) => {
      const outPath = opts.out;

      if (fs.existsSync(outPath) && !opts.force) {
        log.error(`${outPath} already exists. Use --force to overwrite.`);
        process.exit(1);
      }

      const template = opts.template === "devnet" ? ENV_TEMPLATE_DEVNET : ENV_TEMPLATE_FULL;

      fs.writeFileSync(outPath, template);
      log.info(`Created ${outPath} (template: ${opts.template})`);

      // Add to .gitignore if not already
      const gitignorePath = ".gitignore";
      if (fs.existsSync(gitignorePath)) {
        const gi = fs.readFileSync(gitignorePath, "utf-8");
        if (!gi.includes(".env")) {
          fs.appendFileSync(gitignorePath, "\n.env\n.env.*\n");
          log.info("Added .env to .gitignore");
        }
      }
    });

  // ── env check ───────────────────────────────────
  env
    .command("check")
    .description("Validate current environment variables")
    .option("--show-secrets", "Show sensitive values (redacted by default)")
    .option("--file <path>", "Load specific .env file", ".env")
    .action(async (opts) => {
      // Load env file if exists
      const envPath = opts.file;
      const envVars: Record<string, string> = {};

      if (fs.existsSync(envPath)) {
        const content = fs.readFileSync(envPath, "utf-8");
        for (const line of content.split("\n")) {
          const trimmed = line.trim();
          if (!trimmed || trimmed.startsWith("#")) continue;
          const eqIndex = trimmed.indexOf("=");
          if (eqIndex < 0) continue;
          const key = trimmed.slice(0, eqIndex).trim();
          const value = trimmed.slice(eqIndex + 1).trim();
          envVars[key] = value;
        }
      }

      // Merge with process.env
      const merged = { ...envVars, ...process.env };

      const results: Array<{ key: string; status: string; value?: string }> = [];

      // Check required vars
      for (const key of REQUIRED_VARS) {
        const val = merged[key];
        results.push({
          key,
          status: val ? "✓ set" : "✗ MISSING",
          value: val ? (SENSITIVE_VARS.includes(key) && !opts.showSecrets ? "***" : val) : undefined,
        });
      }

      // Check optional vars
      const optionalVars = [
        "SAP_FALLBACK_RPC_URL",
        "SAP_KEYPAIR",
        "SAP_X402_ENDPOINT",
        "SAP_X402_NETWORK",
        "SAP_TOKEN_MINT",
        "SAP_POSTGRES_URL",
        "SAP_REDIS_URL",
      ];

      for (const key of optionalVars) {
        const val = merged[key];
        results.push({
          key,
          status: val ? "✓ set" : "○ unset",
          value: val ? (SENSITIVE_VARS.includes(key) && !opts.showSecrets ? "***" : val) : undefined,
        });
      }

      const missing = results.filter((r) => r.status.includes("MISSING"));

      log.table(results);

      if (missing.length > 0) {
        log.warn(`${missing.length} required variable(s) missing`);
        process.exit(1);
      } else {
        log.info("All required variables are set");
      }
    });

  // ── env keypair ─────────────────────────────────
  const keypair = env
    .command("keypair")
    .description("Keypair operations");

  keypair
    .command("show")
    .description("Show public key from configured keypair")
    .option("--as <format>", "Output format: base58 | json", "base58")
    .action(async (opts) => {
      const kpPath = process.env.SAP_KEYPAIR || program.opts().keypair;

      if (!kpPath) {
        log.error("No keypair configured. Set SAP_KEYPAIR or pass --keypair.");
        process.exit(1);
      }

      try {
        const kp = loadKeypairFromSource(kpPath);
        if (opts.as === "json") {
          output({
            publicKey: kp.publicKey.toBase58(),
            secretKeyPreview: `[${kp.secretKey[0]}, ${kp.secretKey[1]}, ... (${kp.secretKey.length} bytes)]`,
          });
        } else {
          log.info(kp.publicKey.toBase58());
        }
      } catch (err) {
        log.error("Failed to load keypair", { error: (err as Error).message });
        process.exit(1);
      }
    });

  keypair
    .command("generate")
    .description("Generate a new Solana keypair")
    .option("--out <path>", "Save to file (JSON array format)")
    .option("--vanity <prefix>", "Vanity prefix (case-insensitive, slow!)")
    .action(async (opts) => {
      try {
        // Dynamic import to avoid top-level dependency
        const { Keypair } = await import("@solana/web3.js");

        let kp: InstanceType<typeof Keypair>;

        if (opts.vanity) {
          log.info(`Grinding for vanity prefix "${opts.vanity}"... (this may take a while)`);
          const prefix = opts.vanity.toLowerCase();
          let attempts = 0;
          const startTime = Date.now();

          do {
            kp = Keypair.generate();
            attempts++;
            if (attempts % 10000 === 0) {
              const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
              log.info(`  ${attempts} attempts in ${elapsed}s...`);
            }
          } while (!kp!.publicKey.toBase58().toLowerCase().startsWith(prefix));

          log.info(`Found vanity match after ${attempts} attempts`);
        } else {
          kp = Keypair.generate();
        }

        log.info(`Public key: ${kp!.publicKey.toBase58()}`);

        if (opts.out) {
          const dir = path.dirname(opts.out);
          if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
          }
          fs.writeFileSync(opts.out, JSON.stringify(Array.from(kp!.secretKey)));
          fs.chmodSync(opts.out, 0o600);
          log.info(`Keypair saved to ${opts.out} (chmod 600)`);
        } else {
          log.warn("No --out specified. Key exists only in memory.");
        }
      } catch (err) {
        log.error("Keypair generation failed", { error: (err as Error).message });
        process.exit(1);
      }
    });

  keypair
    .command("import <source>")
    .description("Import a keypair from base58 or file")
    .option("--out <path>", "Save to JSON file", "imported-keypair.json")
    .action(async (source: string, opts) => {
      try {
        const kp = loadKeypairFromSource(source);
        log.info(`Imported: ${kp.publicKey.toBase58()}`);

        const dir = path.dirname(opts.out);
        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir, { recursive: true });
        }
        fs.writeFileSync(opts.out, JSON.stringify(Array.from(kp.secretKey)));
        fs.chmodSync(opts.out, 0o600);
        log.info(`Saved to ${opts.out} (chmod 600)`);
      } catch (err) {
        log.error("Import failed", { error: (err as Error).message });
        process.exit(1);
      }
    });
}
